# Generated by Django 2.1.5 on 2022-07-27 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('HA', 'Handyperson services'), ('HO', 'Home visiting'), ('PH', 'Phone calls/Chatting'), ('SO', 'Social activities'), ('TE', 'Technology issues'), ('TR', 'Transportation'), ('OT', 'Others')], default='OT', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OldPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='help',
            name='helper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Helper'),
        ),
        migrations.AddField(
            model_name='help',
            name='oldPerson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.OldPerson'),
        ),
    ]
