# Generated by Django 4.0.2 on 2022-08-13 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='category',
            field=models.CharField(choices=[(None, '----------'), ('HA', 'Handyperson services'), ('HO', 'Home visiting'), ('PH', 'Phone calls/Chatting'), ('SO', 'Social activities'), ('TE', 'Technology issues'), ('TR', 'Transportation'), ('OT', 'Others')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='help',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='help',
            name='helper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.helper'),
        ),
    ]
