# Generated by Django 4.0.2 on 2022-08-13 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_help_category_alter_help_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCandidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.help')),
                ('helper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.helper')),
            ],
        ),
    ]
