# Generated by Django 4.0.2 on 2022-08-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_helpcandidates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
