# Generated by Django 4.0.2 on 2022-08-13 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_help_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
