# Generated by Django 4.0.2 on 2022-08-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_help_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='help',
            old_name='time',
            new_name='dateTime',
        ),
    ]
