# Generated by Django 4.0.2 on 2022-08-15 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_time_help_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='dateTime',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
