# Generated by Django 4.0.2 on 2022-08-15 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_help_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
    ]
