# Generated by Django 4.0.2 on 2022-08-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_help_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
