# Generated by Django 4.0.2 on 2022-08-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_helpcandidates_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpcandidates',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Rejected'), ('3', 'In process'), ('4', 'Finished')], default='3', max_length=1),
        ),
    ]
