# Generated by Django 4.0.2 on 2022-08-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_helpcandidates_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpcandidates',
            name='status',
            field=models.CharField(choices=[('1', 'Accepted'), ('2', 'Rejected'), ('3', 'In process'), ('4', 'Finished')], default='3', max_length=1),
        ),
    ]
