# Generated by Django 4.0.2 on 2022-08-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_helpcandidates_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpcandidates',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='helper',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='oldperson',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
