# Generated by Django 4.0.2 on 2022-08-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_helpcandidates_id_alter_helper_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldperson',
            name='needsHel',
            field=models.BooleanField(default=True),
        ),
    ]
