# Generated by Django 4.0.2 on 2022-08-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_oldperson_needshel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oldperson',
            old_name='needsHel',
            new_name='needsHelp',
        ),
    ]
