# Generated by Django 4.0.2 on 2022-08-17 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailUser1', models.EmailField(max_length=200)),
                ('emailUser2', models.EmailField(blank=True, max_length=200)),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.TextField(max_length=250)),
                ('details', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
