# Generated by Django 4.0.2 on 2022-08-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='title',
        ),
        migrations.AddField(
            model_name='transaction',
            name='action',
            field=models.CharField(default='create', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='model',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
