# Generated by Django 4.0.2 on 2022-08-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_chat_id_call_chat_rename_chat_id_message_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default='Test message', max_length=1000),
            preserve_default=False,
        ),
    ]
